apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name}}
  namespace: {{ .Values.namespace}}
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>Welcome to My Custom Nginx Page</title>
    </head>
    <body>
        <h1>Hello from Kubernetes!</h1>
        <p>This is a custom Nginx v{{ .Values.configmap.data.AppVersion }} served from on {{ .Values.configmap.data.Environment }} environment</p>
    </body>
    </html>
